"""Render docs/atlas.html -- The Global Blueberry Atlas, for trade analysts.

Static, matplotlib-PNG, zero-backend, regenerated by the Monday cron. Reads only
committed atlas CSVs (data/atlas/*) via the atlas modules. Per PRODUCT_SPEC.md:
analyst-first -- the relay/lanes/$/kg/share-shifts lead; the coverage map is the moat.

Sections (built incrementally):
  1. THE YEAR  -- KPI strip · the relay · exporter & importer ladders ·
                  production!=exports · world choropleth.
  (Country profiles + the coverage matrix follow.)

Run: python scripts/build_atlas_site.py
"""
from __future__ import annotations

import base64
import datetime as _dt
import io
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.patches import Polygon as MplPolygon
from matplotlib.collections import PatchCollection
from matplotlib.ticker import FuncFormatter

from atlas import ATLAS_DIR
from atlas import comtrade_sweep as cs
from atlas import comtrade_monthly as cmth
from atlas import comtrade_matrix as cmat
from atlas import countries, faostat, registry

OUT = Path(__file__).resolve().parent.parent / "docs" / "atlas.html"
GEOJSON = ATLAS_DIR / "world_110m.geojson"

# -- palette (editorial, analyst-dense) --
PAPER, INK, SUBTLE = "#faf8f4", "#1d1c1a", "#6c655c"
ACCENT = "#2f6f4e"            # blueberry-green
WARN, BAD, GREY = "#b8860b", "#9c4221", "#b9b3aa"
ORIGIN_COLORS = ["#2f6f4e", "#6a8caf", "#b8860b", "#9c4221", "#7a5c8e", "#4a8a8a",
                 "#a0843c", "#557a55"]


def _style():
    plt.rcParams.update({
        "font.family": "DejaVu Sans", "font.size": 12, "text.color": INK,
        "axes.edgecolor": "#d9d5cf", "axes.labelcolor": SUBTLE,
        "xtick.color": SUBTLE, "ytick.color": SUBTLE, "axes.linewidth": 0.8,
        "figure.dpi": 170,
    })


def _png(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight", facecolor=PAPER, dpi=170)
    plt.close(fig)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


def _bare(ax, grid="y"):
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    ax.tick_params(length=0)
    if grid:
        ax.grid(axis=grid, color="#ece9e4", linewidth=1.0, zorder=0)
        ax.set_axisbelow(True)


# ----------------------------- bridges -----------------------------
def _cc() -> pd.DataFrame:
    return pd.read_csv(ATLAS_DIR / "country_codes.csv")


def _code_to_iso3() -> dict:
    cc = _cc()
    return {int(m): i for m, i in zip(cc["m49"], cc["iso3"]) if isinstance(i, str) and i}


def _faostat_m49_to_iso3() -> dict:
    """True-UN-M49 -> ISO3 from the committed geojson (ISO_N3 -> ISO_A3_EH)."""
    gj = json.loads(GEOJSON.read_text())
    out = {}
    for f in gj["features"]:
        p = f["properties"]
        n3, a3 = p.get("ISO_N3_EH") or p.get("ISO_N3"), p.get("ISO_A3_EH") or p.get("ISO_A3")
        if n3 and a3 and a3 != "-99":
            try:
                out[int(n3)] = a3
            except (TypeError, ValueError):
                pass
    return out


# ----------------------------- data -----------------------------
def _latest_final(role="exporter") -> int:
    return cs.latest_year(role)


def _kpis() -> list[tuple]:
    yr = _latest_final("exporter")
    ex = cs.ranking("exporter", yr); im = cs.ranking("importer", yr)
    exp_prev = cs.ranking("exporter", yr - 1)
    val = ex["value_usd"].sum(); vol = ex["net_kg"].sum()
    top_ex = ex.iloc[0]; top_im = im.iloc[0] if len(im) else None
    # YoY world value
    dv = ""
    if len(exp_prev):
        dv = f" {'▲' if val >= exp_prev['value_usd'].sum() else '▼'}{abs(val/exp_prev['value_usd'].sum()-1)*100:.0f}%"
    out = [
        (f"${val/1e9:.2f}B", f"world exports{dv}"),
        (f"{vol/1e6:.0f}k t", "export volume"),
        (f"{top_ex['country']} {top_ex['share']*100:.0f}%", "top exporter"),
    ]
    if top_im is not None:
        out.append((f"{top_im['country']} {top_im['share']*100:.0f}%", "top importer"))
    out.append((f"{yr}", "latest final year"))
    return out


# ----------------------------- charts -----------------------------
def _relay_png() -> str:
    m = cmth.load()
    if m.empty:
        return ""
    recent = m[m["year"] >= m["year"].max() - 2]
    top = (recent.groupby("exporter")["net_kg"].sum()
           .sort_values(ascending=False).head(6).index.tolist())
    rel = (recent[recent["exporter"].isin(top)]
           .groupby(["month", "exporter"])["net_kg"].sum().unstack(fill_value=0))
    rel = rel.reindex(columns=top).reindex(range(1, 13)).fillna(0)
    share = rel.div(rel.sum(axis=1).replace(0, np.nan), axis=0).fillna(0) * 100
    fig, ax = plt.subplots(figsize=(9.2, 4.0))
    ax.stackplot(range(1, 13), *[share[c] for c in top], labels=top,
                 colors=ORIGIN_COLORS[:len(top)], alpha=0.92)
    ax.set_xlim(1, 12); ax.set_ylim(0, 100)
    ax.set_xticks(range(1, 13))
    ax.set_xticklabels(["J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D"])
    ax.set_yticks([0, 25, 50, 75, 100]); ax.set_yticklabels(["0", "25", "50", "75", "100%"])
    _bare(ax, grid="y")
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.08), ncol=len(top),
              frameon=False, fontsize=10, handlelength=1.0, columnspacing=1.2)
    return _png(fig)


def _ladder_png(role="exporter") -> str:
    yr = _latest_final(role)
    df = cs.ranking(role, yr).head(10).iloc[::-1]
    prev = cs.ranking(role, yr - 1)
    pmap = dict(zip(prev["country"], prev["share"])) if len(prev) else {}
    if df.empty:
        return ""
    fig, ax = plt.subplots(figsize=(4.5, 4.0))
    y = range(len(df))
    ax.barh(y, df["value_usd"] / 1e6, color=ACCENT if role == "exporter" else "#6a8caf",
            height=0.66, zorder=3)
    ax.set_yticks(y); ax.set_yticklabels(df["country"], fontsize=10)
    for i, (_, r) in enumerate(df.iterrows()):
        d = (r["share"] - pmap.get(r["country"], r["share"])) * 100
        arr = "▲" if d > 0.05 else ("▼" if d < -0.05 else "·")
        uv = f" ${r['unit_usd_kg']:.1f}" if r["unit_usd_kg"] > 0 else ""
        ax.text(r["value_usd"] / 1e6, i, f"  {r['share']*100:.0f}% {arr}{uv}",
                va="center", ha="left", fontsize=9, color=SUBTLE)
    ax.set_xlim(0, df["value_usd"].max() / 1e6 * 1.35)
    ax.xaxis.set_major_formatter(FuncFormatter(lambda v, _: f"${v/1000:.1f}B" if v >= 1000 else f"${v:.0f}M"))
    _bare(ax, grid="x")
    return _png(fig)


def _divergence_png() -> str:
    yr = _latest_final("exporter")
    ex = cs.ranking("exporter", yr)[["reporter_code", "country", "value_usd"]]
    c2i = _code_to_iso3()
    ex["iso3"] = ex["reporter_code"].map(c2i)
    fa = faostat.load()
    if fa.empty or ex.empty:
        return ""
    fy = int(fa["year"].max())
    fa = fa[fa["year"] == fy].copy()
    m2i = _faostat_m49_to_iso3()
    fa["iso3"] = fa["m49"].map(m2i)
    j = ex.merge(fa[["iso3", "production_t"]], on="iso3", how="inner")
    j = j[(j["production_t"] > 0) & (j["value_usd"] > 0)]
    if j.empty:
        return ""
    fig, ax = plt.subplots(figsize=(5.2, 4.2))
    ax.scatter(j["production_t"] / 1000, j["value_usd"] / 1e6, s=46, color=ACCENT,
               alpha=0.8, zorder=3, edgecolor="white", linewidth=0.6)
    for _, r in j.iterrows():
        if r["value_usd"] > 1.5e8 or r["production_t"] > 5e4:
            ax.annotate(r["country"], (r["production_t"] / 1000, r["value_usd"] / 1e6),
                        fontsize=8.5, color=INK, xytext=(4, 2), textcoords="offset points")
    ax.set_xlabel("production  (000 t, FAOSTAT)"); ax.set_ylabel("exports  ($M, Comtrade)")
    ax.set_xscale("log"); ax.set_yscale("log")
    _bare(ax, grid="both")
    return _png(fig)


def _choropleth_png() -> str:
    if not GEOJSON.exists():
        return ""
    yr = _latest_final("exporter")
    ex = cs.ranking("exporter", yr)
    c2i = _code_to_iso3()
    val = {}
    for _, r in ex.iterrows():
        iso = c2i.get(int(r["reporter_code"]))
        if iso:
            val[iso] = r["value_usd"]
    if not val:
        return ""
    vmax = np.log10(max(val.values()))
    vmin = np.log10(max(min(val.values()), 1e5))
    cmap = plt.get_cmap("YlGn")
    gj = json.loads(GEOJSON.read_text())
    fig, ax = plt.subplots(figsize=(9.4, 4.6))
    patches, colors = [], []
    for f in gj["features"]:
        iso = f["properties"].get("ISO_A3_EH") or f["properties"].get("ISO_A3")
        geom = f["geometry"]
        if not geom:
            continue
        polys = geom["coordinates"] if geom["type"] == "MultiPolygon" else [geom["coordinates"]]
        v = val.get(iso)
        col = cmap((np.log10(v) - vmin) / (vmax - vmin)) if v else "#ece9e4"
        for poly in polys:
            ring = np.array(poly[0])
            if ring.ndim == 2 and len(ring) >= 3:
                patches.append(MplPolygon(ring, closed=True))
                colors.append(col)
    pc = PatchCollection(patches, facecolor=colors, edgecolor="white", linewidth=0.25)
    ax.add_collection(pc)
    ax.set_xlim(-170, 180); ax.set_ylim(-58, 84)
    ax.set_aspect(1.25); ax.axis("off")
    return _png(fig)


# ----------------------------- the atlas (coverage) -----------------------------
_CATS = [
    ("Flow", ["customs trade detail", "import volume", "bilateral", "re-export",
              "volume chile", "volume peru", "flow + price"]),
    ("Price", ["price", "cif", "fob", "$/kg", "realised", "wholesale", "retail shelf"]),
    ("Production", ["orchard", "planted-area", "area /", "area by", "production", "capacity",
                    "yield", "bearing", "renewal"]),
    ("Phyto", ["phyto", "registered overseas", "authorised export", "packing station"]),
    ("Forecast", ["forecast"]),
    ("Demand", ["retail price", "consumption", "search", "promotion", "scanner", "household",
                "reviews", "own-brand", "market share", "units sold", "grocery"]),
    ("Identity", ["bill of lading", "exporter names", "consignee", "importer identity",
                  "named exporter", "named producer", "cultivar"]),
    ("Condition", ["weather", "ndvi", "drought", "frost", "interception", "interceptions"]),
]
_ACCESS_GLYPH = {"wired": ("✅", "#2f6f4e", "#e7f0ea"),
                 "free": ("🟢", "#2f6f4e", "#f0f5ee"),
                 "paid": ("💷", "#b8860b", "#f7f1e3"),
                 "none": ("⛔", "#9c4221", "#f4eae6"),
                 "": ("·", "#b9b3aa", "#faf8f4")}


def _category(dp: str) -> str | None:
    low = dp.lower()
    for cat, kws in _CATS:
        if any(k in low for k in kws):
            return cat
    return None


def _cell_state(rows: pd.DataFrame) -> str:
    if rows.empty:
        return ""
    if rows["wired"].isin(["yes", "derived"]).any():
        return "wired"
    if (rows["access"] == "free").any():
        return "free"
    if (rows["access"] == "paid").any():
        return "paid"
    return "none"


def _coverage_matrix_html(order: list[str]) -> str:
    df = registry.load()
    df = df[df["country"] != "*"].copy()
    df["cat"] = df["data_point"].map(_category)
    cats = [c for c, _ in _CATS]
    countries_in = [c for c in order if c in set(df["country"])]
    # any catalogued country not in the trade-ordered list -> append
    countries_in += [c for c in sorted(df["country"].unique()) if c not in countries_in]
    head = "".join(f"<th>{c}</th>" for c in cats)
    body = []
    for ctry in countries_in:
        cells = []
        for cat in cats:
            sub = df[(df["country"] == ctry) & (df["cat"] == cat)]
            state = _cell_state(sub)
            g, fg, bg = _ACCESS_GLYPH[state]
            tip = "; ".join(sorted(set(sub["source"]))[:2]) if not sub.empty else ""
            cells.append(f'<td style="background:{bg};color:{fg}" title="{cat}: {tip}">{g}</td>')
        body.append(f'<tr><th class="rh">{ctry}</th>{"".join(cells)}</tr>')
    return (f'<table class="matrix"><thead><tr><th></th>{head}</tr></thead>'
            f'<tbody>{"".join(body)}</tbody></table>')


def _ceiling_html() -> str:
    df = registry.load()
    fw = df["wired"].isin(["yes", "derived"]).sum()
    fu = ((df["access"] == "free") & (~df["wired"].isin(["yes", "derived"]))).sum()
    paid = (df["access"] == "paid").sum()
    none = (df["access"] == "none").sum()
    bars = [("free &amp; wired", fw, "#2f6f4e"), ("free, not yet wired", fu, "#86b08f"),
            ("paid only", paid, "#b8860b"), ("no source (structural gap)", none, "#9c4221")]
    tot = fw + fu + paid + none
    out = ['<div class="ceiling">']
    for label, n, col in bars:
        out.append(f'<div class="cbar"><span>{label}</span>'
                   f'<i style="width:{n/tot*100:.0f}%;background:{col}"></i><b>{n}</b></div>')
    out.append("</div>")
    return "".join(out)


# ----------------------------- country profiles -----------------------------
def _reg_code_map() -> dict:
    cc = _cc()
    n2c = {n: int(m) for m, n in zip(cc["m49"], cc["name"])}
    n2c.update({"Hong Kong": 344, "South Korea": 410})       # registry -> Comtrade aliases
    return n2c


def _faostat_iso() -> pd.DataFrame:
    fa = faostat.load()
    if fa.empty:
        return fa
    fa = fa.copy(); fa["iso3"] = fa["m49"].map(_faostat_m49_to_iso3())
    return fa


def _profile_fig(reg_name, code, cname, iso3, bil, mon, fa_iso, wx) -> str:
    panels = []
    # production trend
    if iso3:
        f = fa_iso[fa_iso["iso3"] == iso3].sort_values("year")
        if len(f) >= 3:
            panels.append(("prod", f))
    # export destinations
    d = bil[(bil["exporter_code"] == code)] if "exporter_code" in bil.columns else bil.iloc[0:0]
    if not d.empty:
        dy = d[d["year"] == d["year"].max()].sort_values("value_usd", ascending=False).head(5)
        if not dy.empty:
            panels.append(("dest", dy))
    # seasonality
    s = mon[mon["exporter"] == cname] if not mon.empty else mon
    if not s.empty:
        prof = (s.groupby(["year", "month"])["net_kg"].sum().reset_index())
        prof["tot"] = prof.groupby("year")["net_kg"].transform("sum")
        prof = prof.groupby("month").apply(lambda x: (x["net_kg"] / x["tot"]).mean()).reindex(range(1, 13)).fillna(0)
        if prof.sum() > 0:
            panels.append(("seas", prof))
    # climate
    w = wx[wx["origin"].isin([reg_name, cname])] if not wx.empty else wx
    if not w.empty:
        clim = w.groupby("month")[["tmin", "t2m"]].mean().reindex(range(1, 13))
        panels.append(("clim", clim))
    if not panels:
        return ""
    n = len(panels)
    fig, axs = plt.subplots(1, n, figsize=(2.7 * n, 2.3))
    axs = np.atleast_1d(axs)
    for ax, (kind, data) in zip(axs, panels):
        if kind == "prod":
            ax.fill_between(data["year"], data["production_t"] / 1000, color=ACCENT, alpha=0.85)
            ax.set_title("production 000t", fontsize=9, color=SUBTLE)
        elif kind == "dest":
            yv = range(len(data))
            ax.barh(yv, data["value_usd"] / 1e6, color="#6a8caf", height=0.6)
            ax.set_yticks(yv); ax.set_yticklabels(data["importer"], fontsize=7.5)
            ax.invert_yaxis(); ax.set_title("top destinations $M", fontsize=9, color=SUBTLE)
        elif kind == "seas":
            ax.fill_between(range(1, 13), data.values * 100, color="#b8860b", alpha=0.85)
            ax.set_xlim(1, 12); ax.set_xticks([1, 4, 7, 10]); ax.set_xticklabels(["J", "A", "J", "O"], fontsize=8)
            ax.set_title("export season %", fontsize=9, color=SUBTLE)
        elif kind == "clim":
            ax.plot(range(1, 13), data["tmin"], color="#6a8caf", lw=1.6)
            ax.axhline(0, color=BAD, lw=0.8, ls=":")
            ax.set_xlim(1, 12); ax.set_xticks([1, 4, 7, 10]); ax.set_xticklabels(["J", "A", "J", "O"], fontsize=8)
            ax.set_title("frost: min °C", fontsize=9, color=SUBTLE)
        _bare(ax, grid="y" if kind in ("prod", "seas", "clim") else "x")
        ax.tick_params(labelsize=8)
    return _png(fig)


def _coverage_card_html(reg_name: str, df: pd.DataFrame) -> str:
    sub = df[df["country"] == reg_name]
    if sub.empty:
        return ""
    fw = sub["wired"].isin(["yes", "derived"]).sum()
    fu = ((sub["access"] == "free") & (~sub["wired"].isin(["yes", "derived"]))).sum()
    paid = (sub["access"] == "paid").sum()
    none = (sub["access"] == "none").sum()
    gaps = sub[sub["access"].isin(["paid", "none"])]["data_point"].head(2).tolist()
    gap_txt = (" · gap: " + "; ".join(gaps)) if gaps else ""
    return (f'<div class="cov"><span class="g">✅ {fw} wired</span>'
            f'<span class="g2">🟢 {fu} free</span>'
            f'<span class="p">💷 {paid}</span><span class="n">⛔ {none}</span>'
            f'<em>{gap_txt}</em></div>')


def _country_sections(order: list[str]) -> str:
    reg = registry.load()
    n2c = _reg_code_map()
    c2i = _code_to_iso3()
    bil, mon, wx = cmat.load(), cmth.load(), _wx_load()
    fa_iso = _faostat_iso()
    reg_countries = [c for c in order if c in set(reg["country"])]
    reg_countries += [c for c in sorted(reg["country"].unique())
                      if c not in reg_countries and c != "*"]
    out = []
    for name in reg_countries:
        code = n2c.get(name)
        cname = countries.name(code) if code else name
        iso3 = c2i.get(code) if code else None
        fig = _profile_fig(name, code, cname, iso3, bil, mon, fa_iso, wx) if code else ""
        card = _coverage_card_html(name, reg)
        if not fig and not card:
            continue
        img = f'<img src="{fig}" alt="{name}"/>' if fig else '<p class="lead">No wired data panels yet — see coverage.</p>'
        out.append(f'<div class="profile"><h3>{name}</h3>{card}{img}</div>')
    return "".join(out)


def _wx_load():
    try:
        from atlas import nasa_power
        return nasa_power.load()
    except Exception:
        return pd.DataFrame()


def _trade_order() -> list[str]:
    """Registry countries ordered by trade importance (max of export/import value)."""
    reg = registry.load()
    n2c = _reg_code_map()
    score = {}
    for role in ("exporter", "importer"):
        r = cs.ranking(role)
        vmap = dict(zip(r["country"], r["value_usd"]))
        for name in reg["country"].unique():
            if name == "*":
                continue
            code = n2c.get(name)
            cn = countries.name(code) if code else name
            score[name] = max(score.get(name, 0), vmap.get(cn, 0))
    return [c for c, _ in sorted(score.items(), key=lambda kv: -kv[1])]


# ----------------------------- assembly -----------------------------
def _stamp(txt: str) -> str:
    return f'<p class="stamp">{txt}</p>'


def _fig_block(title: str, png: str, stamp: str, lead: str = "") -> str:
    if not png:
        return ""
    lead_html = f'<p class="lead">{lead}</p>' if lead else ""
    return (f'<div class="fig"><h3>{title}</h3>{lead_html}'
            f'<img src="{png}" alt="{title}"/>{_stamp(stamp)}</div>')


def build() -> Path:
    _style()
    today = _dt.date.today().isoformat()
    yr = _latest_final("exporter")

    kpis = "".join(f'<div class="kpi"><b>{v}</b><span>{l}</span></div>' for v, l in _kpis())

    the_year = "".join([
        _fig_block("The relay — who supplies the world each month",
                   _relay_png(),
                   "UN Comtrade monthly · supply-side export volume · free",
                   "Chile owns Jan–Feb, Spain the Northern spring, the US &amp; Canada the "
                   "summer, and Peru the great counter-season surge of Sep–Nov."),
        '<div class="row">',
        _fig_block(f"Top exporters {yr}", _ladder_png("exporter"),
                   f"UN Comtrade · {yr} (final) · free · ✓{today}"),
        _fig_block(f"Top importers {yr}", _ladder_png("importer"),
                   f"UN Comtrade · {yr} (final) · free · ✓{today}"),
        '</div>',
        '<div class="row">',
        _fig_block("Production ≠ exports", _divergence_png(),
                   "FAOSTAT × UN Comtrade · free",
                   "Who grows to eat vs. grows to ship vs. ships without growing."),
        _fig_block(f"World exporters {yr}", _choropleth_png(),
                   "UN Comtrade · export value · free"),
        '</div>',
    ])

    order = _trade_order()
    profiles = _country_sections(order)
    matrix = _coverage_matrix_html(order)
    ceiling = _ceiling_html()

    html = _PAGE.format(today=today, year=yr, kpis=kpis, the_year=the_year,
                        profiles=profiles, matrix=matrix, ceiling=ceiling,
                        n_countries=profiles.count('class="profile"'))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(html, encoding="utf-8")
    return OUT


_PAGE = """<!doctype html><html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>The Global Blueberry Atlas</title>
<style>
:root{{--paper:#faf8f4;--ink:#1d1c1a;--subtle:#6c655c;--accent:#2f6f4e;--line:#e6e2db}}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--paper);color:var(--ink);
 font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;line-height:1.5}}
header{{padding:34px 22px 10px;max-width:1060px;margin:0 auto}}
h1{{font-family:Georgia,serif;font-size:2.3rem;margin:0 0 4px}}
.sub{{color:var(--subtle);font-size:1.02rem;margin:0 0 18px}}
.kpis{{display:flex;flex-wrap:wrap;gap:10px;margin:6px 0 4px}}
.kpi{{background:#fff;border:1px solid var(--line);border-radius:10px;padding:10px 14px;min-width:120px}}
.kpi b{{display:block;font-size:1.25rem}} .kpi span{{color:var(--subtle);font-size:.82rem}}
main{{max-width:1060px;margin:0 auto;padding:8px 22px 60px}}
h2{{font-family:Georgia,serif;font-size:1.5rem;margin:34px 0 4px;border-top:2px solid var(--ink);padding-top:10px}}
.fig{{background:#fff;border:1px solid var(--line);border-radius:12px;padding:14px 16px;margin:14px 0;flex:1}}
.fig h3{{font-size:1.06rem;margin:0 0 2px}}
.fig img{{width:100%;height:auto;display:block;margin:6px 0 2px}}
.lead{{color:var(--subtle);font-size:.92rem;margin:0 0 4px}}
.row{{display:flex;gap:14px;flex-wrap:wrap}} .row .fig{{min-width:300px}}
.stamp{{color:#a59e93;font-size:.74rem;margin:4px 0 0;font-variant:small-caps;letter-spacing:.3px}}
nav{{max-width:1060px;margin:0 auto;padding:0 22px}}
nav a{{color:var(--accent);text-decoration:none;font-weight:600;margin-right:18px;font-size:.95rem}}
.profiles{{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}}
.profile{{background:#fff;border:1px solid var(--line);border-radius:12px;padding:12px 14px}}
.profile h3{{font-size:1.02rem;margin:0 0 4px}} .profile img{{width:100%;height:auto}}
.cov{{font-size:.78rem;color:var(--subtle);margin:0 0 6px}}
.cov span{{margin-right:8px;font-weight:600}} .cov .g{{color:#2f6f4e}} .cov .g2{{color:#86b08f}}
.cov .p{{color:#b8860b}} .cov .n{{color:#9c4221}} .cov em{{display:block;color:#a59e93;font-style:normal;margin-top:2px}}
.matrix{{border-collapse:collapse;font-size:.92rem;width:100%}}
.matrix th{{font-weight:600;padding:5px 7px;text-align:center;color:var(--subtle);font-size:.8rem}}
.matrix th.rh{{text-align:right;white-space:nowrap;color:var(--ink);font-size:.84rem}}
.matrix td{{text-align:center;padding:5px 7px;border:1px solid #efece6;font-size:1rem}}
.ceiling{{margin:6px 0 2px}} .cbar{{display:flex;align-items:center;gap:10px;margin:5px 0;font-size:.86rem}}
.cbar span{{width:170px;color:var(--subtle)}} .cbar i{{height:14px;border-radius:3px;display:inline-block}} .cbar b{{color:var(--ink)}}
footer{{max-width:1060px;margin:0 auto;padding:20px 22px 50px;color:var(--subtle);font-size:.82rem;border-top:1px solid var(--line)}}
</style></head><body>
<header>
<h1>The Global Blueberry Atlas</h1>
<p class="sub">What the world grows, ships, and pays through the year — and exactly what
you can know about it for free. <b>Reference year {year}.</b></p>
<div class="kpis">{kpis}</div>
</header>
<nav><a href="#year">The year</a><a href="#countries">Countries</a><a href="#atlas">The atlas</a><a href="./index.html">Deep dive: UK ↗</a></nav>
<main>
<h2 id="year">The year</h2>
{the_year}
<h2 id="countries">Countries &amp; coverage <span style="font-size:.8rem;color:#a59e93">({n_countries} profiles)</span></h2>
<p class="lead">Each country's wired data (production · destinations · season · frost) beside
its coverage card — what's free-and-held (✅), free-but-unwired (🟢), paid (💷), or absent (⛔).</p>
<div class="profiles">{profiles}</div>
<h2 id="atlas">The atlas — what you can know</h2>
<p class="lead">The registry as a map: every country × data-class, flagged by access. This —
not the data — is what no one else publishes.</p>
{ceiling}
{matrix}
</main>
<footer>
Built {today} from free, public sources (UN Comtrade · FAOSTAT · USDA-FAS · NASA POWER ·
Eurostat · national NPPOs). Every figure is stamped with its source and access. Latest
~2 years of trade are provisional. · The Global Blueberry Atlas · fruit is a parameter.
</footer>
</body></html>"""


if __name__ == "__main__":
    p = build()
    kb = p.stat().st_size / 1024
    print(f"wrote {p}  ({kb:.0f} KB)")
