"""Render docs/atlas.html -- The Global Blueberry Atlas, for trade analysts.

Static, matplotlib-PNG, zero-backend, regenerated by the Monday cron. Reads only
committed atlas CSVs (data/atlas/*) via the atlas modules. Per PRODUCT_SPEC.md:
analyst-first -- the relay/lanes/$/kg/share-shifts lead; the coverage map is the moat.

Sections (built incrementally):
  1. THE YEAR  -- KPI strip · the relay · exporter & importer ladders ·
                  production!=exports · world choropleth.
  (Country profiles + the coverage matrix follow.)

Run: python scripts/build_atlas_site.py
"""
from __future__ import annotations

import base64
import datetime as _dt
import io
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.patches import Polygon as MplPolygon
from matplotlib.collections import PatchCollection
from matplotlib.ticker import FuncFormatter

from atlas import ATLAS_DIR
from atlas import comtrade_sweep as cs
from atlas import comtrade_monthly as cmth
from atlas import comtrade_matrix as cmat
from atlas import countries, faostat, registry

OUT = Path(__file__).resolve().parent.parent / "docs" / "atlas.html"
GEOJSON = ATLAS_DIR / "world_110m.geojson"

# -- palette (editorial, analyst-dense) --
PAPER, INK, SUBTLE = "#faf8f4", "#1d1c1a", "#6c655c"
ACCENT = "#2f6f4e"            # blueberry-green
WARN, BAD, GREY = "#b8860b", "#9c4221", "#b9b3aa"
ORIGIN_COLORS = ["#2f6f4e", "#6a8caf", "#b8860b", "#9c4221", "#7a5c8e", "#4a8a8a",
                 "#a0843c", "#557a55"]


def _style():
    plt.rcParams.update({
        "font.family": "DejaVu Sans", "font.size": 12, "text.color": INK,
        "axes.edgecolor": "#d9d5cf", "axes.labelcolor": SUBTLE,
        "xtick.color": SUBTLE, "ytick.color": SUBTLE, "axes.linewidth": 0.8,
        "figure.dpi": 170,
    })


def _png(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight", facecolor=PAPER, dpi=170)
    plt.close(fig)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


def _bare(ax, grid="y"):
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    ax.tick_params(length=0)
    if grid:
        ax.grid(axis=grid, color="#ece9e4", linewidth=1.0, zorder=0)
        ax.set_axisbelow(True)


# ----------------------------- bridges -----------------------------
def _cc() -> pd.DataFrame:
    return pd.read_csv(ATLAS_DIR / "country_codes.csv")


def _code_to_iso3() -> dict:
    cc = _cc()
    return {int(m): i for m, i in zip(cc["m49"], cc["iso3"]) if isinstance(i, str) and i}


def _faostat_m49_to_iso3() -> dict:
    """True-UN-M49 -> ISO3 from the committed geojson (ISO_N3 -> ISO_A3_EH)."""
    gj = json.loads(GEOJSON.read_text())
    out = {}
    for f in gj["features"]:
        p = f["properties"]
        n3, a3 = p.get("ISO_N3_EH") or p.get("ISO_N3"), p.get("ISO_A3_EH") or p.get("ISO_A3")
        if n3 and a3 and a3 != "-99":
            try:
                out[int(n3)] = a3
            except (TypeError, ValueError):
                pass
    return out


# ----------------------------- data -----------------------------
def _latest_final(role="exporter") -> int:
    return cs.latest_year(role)


def _kpis() -> list[tuple]:
    yr = _latest_final("exporter")
    ex = cs.ranking("exporter", yr); im = cs.ranking("importer", yr)
    exp_prev = cs.ranking("exporter", yr - 1)
    val = ex["value_usd"].sum(); vol = ex["net_kg"].sum()
    top_ex = ex.iloc[0]; top_im = im.iloc[0] if len(im) else None
    # YoY world value
    dv = ""
    if len(exp_prev):
        dv = f" {'▲' if val >= exp_prev['value_usd'].sum() else '▼'}{abs(val/exp_prev['value_usd'].sum()-1)*100:.0f}%"
    out = [
        (f"${val/1e9:.2f}B", f"world exports{dv}"),
        (f"{vol/1e6:.0f}k t", "export volume"),
        (f"{top_ex['country']} {top_ex['share']*100:.0f}%", "top exporter"),
    ]
    if top_im is not None:
        out.append((f"{top_im['country']} {top_im['share']*100:.0f}%", "top importer"))
    out.append((f"{yr}", "latest final year"))
    return out


# ----------------------------- charts -----------------------------
def _relay_png() -> str:
    m = cmth.load()
    if m.empty:
        return ""
    recent = m[m["year"] >= m["year"].max() - 2]
    top = (recent.groupby("exporter")["net_kg"].sum()
           .sort_values(ascending=False).head(6).index.tolist())
    rel = (recent[recent["exporter"].isin(top)]
           .groupby(["month", "exporter"])["net_kg"].sum().unstack(fill_value=0))
    rel = rel.reindex(columns=top).reindex(range(1, 13)).fillna(0)
    share = rel.div(rel.sum(axis=1).replace(0, np.nan), axis=0).fillna(0) * 100
    fig, ax = plt.subplots(figsize=(9.2, 4.0))
    ax.stackplot(range(1, 13), *[share[c] for c in top], labels=top,
                 colors=ORIGIN_COLORS[:len(top)], alpha=0.92)
    ax.set_xlim(1, 12); ax.set_ylim(0, 100)
    ax.set_xticks(range(1, 13))
    ax.set_xticklabels(["J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D"])
    ax.set_yticks([0, 25, 50, 75, 100]); ax.set_yticklabels(["0", "25", "50", "75", "100%"])
    _bare(ax, grid="y")
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.08), ncol=len(top),
              frameon=False, fontsize=10, handlelength=1.0, columnspacing=1.2)
    return _png(fig)


def _ladder_png(role="exporter") -> str:
    yr = _latest_final(role)
    df = cs.ranking(role, yr).head(10).iloc[::-1]
    prev = cs.ranking(role, yr - 1)
    pmap = dict(zip(prev["country"], prev["share"])) if len(prev) else {}
    if df.empty:
        return ""
    fig, ax = plt.subplots(figsize=(4.5, 4.0))
    y = range(len(df))
    ax.barh(y, df["value_usd"] / 1e6, color=ACCENT if role == "exporter" else "#6a8caf",
            height=0.66, zorder=3)
    ax.set_yticks(y); ax.set_yticklabels(df["country"], fontsize=10)
    for i, (_, r) in enumerate(df.iterrows()):
        d = (r["share"] - pmap.get(r["country"], r["share"])) * 100
        arr = "▲" if d > 0.05 else ("▼" if d < -0.05 else "·")
        uv = f" ${r['unit_usd_kg']:.1f}" if r["unit_usd_kg"] > 0 else ""
        ax.text(r["value_usd"] / 1e6, i, f"  {r['share']*100:.0f}% {arr}{uv}",
                va="center", ha="left", fontsize=9, color=SUBTLE)
    ax.set_xlim(0, df["value_usd"].max() / 1e6 * 1.35)
    ax.xaxis.set_major_formatter(FuncFormatter(lambda v, _: f"${v/1000:.1f}B" if v >= 1000 else f"${v:.0f}M"))
    _bare(ax, grid="x")
    return _png(fig)


def _divergence_png() -> str:
    yr = _latest_final("exporter")
    ex = cs.ranking("exporter", yr)[["reporter_code", "country", "value_usd"]]
    c2i = _code_to_iso3()
    ex["iso3"] = ex["reporter_code"].map(c2i)
    fa = faostat.load()
    if fa.empty or ex.empty:
        return ""
    fy = int(fa["year"].max())
    fa = fa[fa["year"] == fy].copy()
    m2i = _faostat_m49_to_iso3()
    fa["iso3"] = fa["m49"].map(m2i)
    j = ex.merge(fa[["iso3", "production_t"]], on="iso3", how="inner")
    j = j[(j["production_t"] > 0) & (j["value_usd"] > 0)]
    if j.empty:
        return ""
    fig, ax = plt.subplots(figsize=(5.2, 4.2))
    ax.scatter(j["production_t"] / 1000, j["value_usd"] / 1e6, s=46, color=ACCENT,
               alpha=0.8, zorder=3, edgecolor="white", linewidth=0.6)
    for _, r in j.iterrows():
        if r["value_usd"] > 1.5e8 or r["production_t"] > 5e4:
            ax.annotate(r["country"], (r["production_t"] / 1000, r["value_usd"] / 1e6),
                        fontsize=8.5, color=INK, xytext=(4, 2), textcoords="offset points")
    # China -- the world #1 producer FAOSTAT misses: grows 810kt, exports ~nothing
    try:
        from atlas import china
        cp = china.latest("production", "China total")
        ce = ex[ex["country"] == "China"]["value_usd"]
        if cp and len(ce):
            ax.scatter([cp / 1000], [ce.iloc[0] / 1e6], s=80, color="#9c4221", zorder=5,
                       edgecolor="white", linewidth=0.7)
            ax.annotate("China (#1 grower, barely exports)", (cp / 1000, ce.iloc[0] / 1e6),
                        fontsize=8.5, color="#9c4221", fontweight="bold",
                        xytext=(-150, 6), textcoords="offset points")
    except Exception:
        pass
    ax.set_xlabel("production  (000 t · FAOSTAT + China snapshot)"); ax.set_ylabel("exports  ($M, Comtrade)")
    ax.set_xscale("log"); ax.set_yscale("log")
    _bare(ax, grid="both")
    return _png(fig)


def _choropleth_png() -> str:
    if not GEOJSON.exists():
        return ""
    yr = _latest_final("exporter")
    ex = cs.ranking("exporter", yr)
    c2i = _code_to_iso3()
    val = {}
    for _, r in ex.iterrows():
        iso = c2i.get(int(r["reporter_code"]))
        if iso:
            val[iso] = r["value_usd"]
    if not val:
        return ""
    vmax = np.log10(max(val.values()))
    vmin = np.log10(max(min(val.values()), 1e5))
    cmap = plt.get_cmap("YlGn")
    gj = json.loads(GEOJSON.read_text())
    fig, ax = plt.subplots(figsize=(9.4, 4.6))
    patches, colors = [], []
    for f in gj["features"]:
        iso = f["properties"].get("ISO_A3_EH") or f["properties"].get("ISO_A3")
        geom = f["geometry"]
        if not geom:
            continue
        polys = geom["coordinates"] if geom["type"] == "MultiPolygon" else [geom["coordinates"]]
        v = val.get(iso)
        col = cmap((np.log10(v) - vmin) / (vmax - vmin)) if v else "#ece9e4"
        for poly in polys:
            ring = np.array(poly[0])
            if ring.ndim == 2 and len(ring) >= 3:
                patches.append(MplPolygon(ring, closed=True))
                colors.append(col)
    pc = PatchCollection(patches, facecolor=colors, edgecolor="white", linewidth=0.25)
    ax.add_collection(pc)
    ax.set_xlim(-170, 180); ax.set_ylim(-58, 84)
    ax.set_aspect(1.25); ax.axis("off")
    return _png(fig)


# ----------------------------- the atlas (coverage) -----------------------------
_CATS = [
    ("Flow", ["customs trade detail", "import volume", "bilateral", "re-export",
              "volume chile", "volume peru", "flow + price"]),
    ("Price", ["price", "cif", "fob", "$/kg", "realised", "wholesale", "retail shelf"]),
    ("Production", ["orchard", "planted-area", "area /", "area by", "production", "capacity",
                    "yield", "bearing", "renewal"]),
    ("Phyto", ["phyto", "registered overseas", "authorised export", "packing station"]),
    ("Forecast", ["forecast"]),
    ("Demand", ["retail price", "consumption", "search", "promotion", "scanner", "household",
                "reviews", "own-brand", "market share", "units sold", "grocery"]),
    ("Identity", ["bill of lading", "exporter names", "consignee", "importer identity",
                  "named exporter", "named producer", "cultivar"]),
    ("Condition", ["weather", "ndvi", "drought", "frost", "interception", "interceptions"]),
]
_ACCESS_GLYPH = {"wired": ("✅", "#2f6f4e", "#e7f0ea"),
                 "free": ("🟢", "#2f6f4e", "#f0f5ee"),
                 "paid": ("💷", "#b8860b", "#f7f1e3"),
                 "none": ("⛔", "#9c4221", "#f4eae6"),
                 "": ("·", "#b9b3aa", "#faf8f4")}


def _category(dp: str) -> str | None:
    low = dp.lower()
    for cat, kws in _CATS:
        if any(k in low for k in kws):
            return cat
    return None


def _cell_state(rows: pd.DataFrame) -> str:
    if rows.empty:
        return ""
    if rows["wired"].isin(["yes", "derived"]).any():
        return "wired"
    if (rows["access"] == "free").any():
        return "free"
    if (rows["access"] == "paid").any():
        return "paid"
    return "none"


def _coverage_matrix_html(order: list[str]) -> str:
    df = registry.load()
    df = df[df["country"] != "*"].copy()
    df["cat"] = df["data_point"].map(_category)
    cats = [c for c, _ in _CATS]
    countries_in = [c for c in order if c in set(df["country"])]
    # any catalogued country not in the trade-ordered list -> append
    countries_in += [c for c in sorted(df["country"].unique()) if c not in countries_in]
    head = "".join(f"<th>{c}</th>" for c in cats)
    body = []
    for ctry in countries_in:
        cells = []
        for cat in cats:
            sub = df[(df["country"] == ctry) & (df["cat"] == cat)]
            state = _cell_state(sub)
            g, fg, bg = _ACCESS_GLYPH[state]
            tip = "; ".join(sorted(set(sub["source"]))[:2]) if not sub.empty else ""
            cells.append(f'<td style="background:{bg};color:{fg}" title="{cat}: {tip}">{g}</td>')
        body.append(f'<tr><th class="rh">{ctry}</th>{"".join(cells)}</tr>')
    return (f'<table class="matrix"><thead><tr><th></th>{head}</tr></thead>'
            f'<tbody>{"".join(body)}</tbody></table>')


def _ceiling_html() -> str:
    b = registry.coverage_buckets()
    bars = [
        ("held — free &amp; wired", b["held"], "#2f6f4e"),
        ("axis covered by a base layer*", b["base_covered"], "#6f9e7e"),
        ("true headroom (unwired, mostly fragile)", b["headroom"], "#b8a86a"),
        ("info-only — not a dataset", b["info_only"], "#c9c2b6"),
        ("paid only", b["paid"], "#b8860b"),
        ("no source (structural gap)", b["none"], "#9c4221"),
    ]
    tot = sum(n for _, n, _ in bars)
    out = ['<div class="ceiling">']
    for label, n, col in bars:
        out.append(f'<div class="cbar"><span>{label}</span>'
                   f'<i style="width:{n/tot*100:.0f}%;background:{col}"></i><b>{n}</b></div>')
    out.append('<p class="stamp">*national customs → Comtrade/COMEXT · national area → '
               'FAOSTAT · weather → NASA POWER: the data-point’s axis is already measured '
               'globally; the national source would add only granularity, not new signal.</p>')
    out.append("</div>")
    return "".join(out)


# ----------------------------- country profiles -----------------------------
def _reg_code_map() -> dict:
    cc = _cc()
    n2c = {n: int(m) for m, n in zip(cc["m49"], cc["name"])}
    n2c.update({"Hong Kong": 344, "South Korea": 410})       # registry -> Comtrade aliases
    return n2c


def _faostat_iso() -> pd.DataFrame:
    fa = faostat.load()
    if fa.empty:
        return fa
    fa = fa.copy(); fa["iso3"] = fa["m49"].map(_faostat_m49_to_iso3())
    return fa


def _country_fig(name, code, ex, im, primary, bil, named) -> str:
    """Adaptive card figure: dual-flow volume · labelled price · dual partner graph ·
    named-exporter depth (where it exists). Panels render only when they have data."""
    panels = ["vol", "price"]
    Y = int(bil["year"].max()) if len(bil) else None
    dest = (bil[(bil["exporter_code"] == code) & (bil["year"] == Y)]
            .groupby("importer")["value_usd"].sum().nlargest(4)) if code else pd.Series(dtype=float)
    orig = (bil[(bil["importer_code"] == code) & (bil["year"] == Y)]
            .groupby("exporter")["value_usd"].sum().nlargest(4)) if code else pd.Series(dtype=float)
    if len(dest) or len(orig):
        panels.append("partners")
    if named is not None and len(named):
        panels.append("named")
    n = len(panels)
    fig, axs = plt.subplots(1, n, figsize=(2.8 * n, 2.15))
    axs = np.atleast_1d(axs)
    for ax, p in zip(axs, panels):
        if p == "vol":
            series = [s for s in (("exports", ex, ACCENT), ("imports", im, "#6a8caf")) if len(s[1])]
            for label, d, col in series:
                vy = (d["net_kg"] / 1e6).where(d["net_kg"] > 0)     # mask quantity-gap years
                ax.plot(d["year"], vy, color=col, lw=1.8, label=label, zorder=4)
            if len(series) == 2:                                    # fill the SMALLER flow
                small = min(series, key=lambda s: s[1]["net_kg"].iloc[-1])
                ax.fill_between(small[1]["year"], (small[1]["net_kg"] / 1e6).where(small[1]["net_kg"] > 0),
                                color=small[2], alpha=0.32, zorder=2)
                ax.legend(fontsize=7, frameon=False, loc="upper left", handlelength=1.0)
            elif series:
                d, col = series[0][1], series[0][2]
                ax.fill_between(d["year"], (d["net_kg"] / 1e6).where(d["net_kg"] > 0),
                                color=col, alpha=0.85, zorder=2)
            yrs = sorted(set(ex["year"].tolist() + im["year"].tolist()))
            ax.set_xticks([yrs[0], yrs[-1]] if yrs else []); ax.set_ylim(bottom=0)
            ax.set_title("volume · kt", fontsize=9.5, color=SUBTLE, loc="left")
        elif p == "price":
            d = ex if primary == "exporter" else im
            py = d["unit_usd_kg"].where(d["net_kg"] > 0)            # $/kg is meaningless where qty=0
            ax.plot(d["year"], py, color="#b8860b", lw=2.0, marker="o", ms=3, zorder=4)
            ax.set_xticks([int(d["year"].min()), int(d["year"].max())])
            ax.set_title(f"avg $/kg · customs {'FOB' if primary=='exporter' else 'CIF'}",
                         fontsize=9.5, color=SUBTLE, loc="left")
        elif p == "partners":
            labels, vals, cols = [], [], []
            for c, v in dest.items():
                labels.append(f"▸ {c}"); vals.append(v / 1e6); cols.append(ACCENT)
            for c, v in orig.items():
                labels.append(f"◂ {c}"); vals.append(v / 1e6); cols.append("#6a8caf")
            yy = list(range(len(labels)))
            ax.barh(yy, vals, color=cols, height=0.72)
            ax.set_yticks(yy); ax.set_yticklabels(labels, fontsize=7.5); ax.invert_yaxis()
            ax.set_title("sells to ▸ / buys from ◂ · $M", fontsize=8.8, color=SUBTLE, loc="left")
        elif p == "named":
            t = named.head(6)
            yy = list(range(len(t)))
            ax.barh(yy, t["volume_t"] / 1000, color="#7a5c8e", height=0.72)
            ax.set_yticks(yy); ax.set_yticklabels(t["company"], fontsize=7.5); ax.invert_yaxis()
            ax.set_title("named exporters · kt", fontsize=8.8, color=SUBTLE, loc="left")
        _bare(ax, grid="y" if p in ("vol", "price") else "x")
        ax.tick_params(labelsize=8.2)
    return _png(fig)


def _extra_facts(name, code, iso3, fa_iso, wx) -> list[str]:
    """Adaptive 'small facts' — only the ones that exist for this country."""
    out = []
    try:                                                  # the real-time campaign layer leads
        if name == "South Africa":                        # live-parsed weekly PDF
            from atlas import berriesza
            h = berriesza.headline()
            if h:
                out.append(f'<b style="color:#2f6f4e">current season — {h}</b>')
                reg = berriesza.load()
                reg = reg[reg["region"] != "Total"].sort_values("total_t", ascending=False).head(3)
                if len(reg):
                    out.append("by region: " + ", ".join(f"{r['region']} {r['total_t']/1000:.0f}kt"
                                                          for _, r in reg.iterrows()))
        else:
            from atlas import campaigns
            h = campaigns.headline(name)
            if h:
                out.append(f'<b style="color:#2f6f4e">current season — {h}</b>')
    except Exception:
        pass
    produced = False
    if iso3 is not None:
        f = fa_iso[fa_iso["iso3"] == iso3]
        if len(f):
            fl = f.sort_values("year").iloc[-1]
            out.append(f"produces <b>{fl['production_t']/1000:.0f} kt</b> ({fl['yield_t_ha']:.1f} t/ha)")
            produced = True
    if not produced and name != "China":                  # FAOSTAT-missing producers (SA, Argentina)
        try:
            from atlas import production
            p = production.latest(name, "production")
            if p:
                out.append(f"produces ~<b>{p/1000:.0f} kt</b> (snapshot — FAOSTAT-missing)")
        except Exception:
            pass
    try:
        from atlas import usda_gain
        fc = usda_gain.load()
        fc = fc[(fc["country"] == name) & (fc["metric"] == "production")]
        if len(fc):
            out.append(f"forecast <b>{fc.iloc[0]['value_mt']/1000:.0f} kt</b> ({int(fc.iloc[0]['year'])})")
    except Exception:
        pass
    w = wx[wx["origin"] == name] if not wx.empty else wx
    if not w.empty:
        cold = w.groupby("month")["tmin"].mean().min()
        out.append("frost-free" if cold > 1 else f"frost risk (min {cold:.0f}°C)")
    if name == "China":                                  # the gated bloc, as a press snapshot
        try:
            from atlas import china
            h = china.headline()
            if h:
                out.append(f'<b style="color:#2f6f4e">{h}</b>')
        except Exception:
            pass
    if name == "USA":                                     # unique AMS view: US supply by origin
        try:
            from atlas import usda_movement
            mv = usda_movement.load()
            if len(mv):
                rd = str(mv["report_date"].iloc[0])[:7]
                top = mv.sort_values("season_t", ascending=False).head(4)
                bits = ", ".join(f"{r['origin']} {r['season_t']/1000:.0f}kt" for _, r in top.iterrows())
                out.append(f"US supply by origin (AMS to {rd}): {bits}")
        except Exception:
            pass
    try:
        from atlas import senasica
        o = senasica.load(fruit="Arándano")
        if name == "Mexico" and len(o):
            out.append(f"<b>{len(o)}</b> named export orchards")
    except Exception:
        pass
    return out


def _slug(name: str) -> str:
    return "c-" + re.sub(r"[^a-z0-9]", "", name.lower())


def _country_card(name, code, cname, iso3, reg, fa_iso, wx, bil) -> str:
    sub = cs.load()
    sub = sub[sub["reporter_code"] == code] if code else sub.iloc[0:0]
    ex = sub[sub["role"] == "exporter"].sort_values("year")
    im = sub[sub["role"] == "importer"].sort_values("year")
    lv = lambda d: float(d["value_usd"].iloc[-1]) if len(d) else 0.0
    role, ts, verb = ("exporter", ex, "export") if lv(ex) >= lv(im) else ("importer", im, "import")
    cov = _coverage_card_html(name, reg)
    sid = _slug(name)
    if ts.empty:
        return (f'<div class="profile" id="{sid}"><h3>{name}</h3>{cov}'
                f'<p class="lead">No trade series yet (small / non-reporting market).</p></div>')
    tsq = ts[ts["net_kg"] > 0]                            # headline from years with real quantity
    tsq = tsq if len(tsq) else ts
    last, first = tsq.iloc[-1], tsq.iloc[0]
    prov = cs.is_provisional(int(last["year"]))           # compute fresh (column is baked at fetch)
    yoy = (last["net_kg"] / tsq.iloc[-2]["net_kg"] - 1) * 100 if len(tsq) >= 2 and tsq.iloc[-2]["net_kg"] else None
    grow = (last["net_kg"] / first["net_kg"] - 1) * 100 if len(tsq) >= 2 and first["net_kg"] else None
    val = last["value_usd"]; vstr = f"${val/1e9:.2f}B" if val >= 1e9 else f"${val/1e6:.0f}M"
    def stat(b, l):
        return f'<div><b>{b}</b><span>{l}</span></div>'
    yoy_s = f' <i class="{"up" if yoy>=0 else "dn"}">{"▲" if yoy>=0 else "▼"}{abs(yoy):.0f}%</i>' if yoy is not None else ""
    strip = ('<div class="stats">'
             + stat(f"{last['net_kg']/1e6:.0f} kt", f"{verb} vol {int(last['year'])}{' ·prov' if prov else ''}{yoy_s}")
             + stat(vstr, "value")
             + stat(f"${last['unit_usd_kg']:.2f}", "$/kg")
             + stat(f"{last['share']*100:.0f}%", f"world share · #{int(last['rank'])}")
             + (stat(f"{'+' if grow>=0 else ''}{grow:.0f}%", f"since {int(first['year'])}") if grow is not None else "")
             + "</div>")
    named = None
    if name == "Peru":
        from atlas import peru_exporters
        named = peru_exporters.load()
    img = f'<img src="{_country_fig(name, code, ex, im, role, bil, named)}"/>'
    facts = _extra_facts(name, code, iso3, fa_iso, wx)
    deep = '<a href="./index.html">deep dive ↗</a>' if name in ("United Kingdom", "Chile", "Peru") else ""
    facts_html = f'<p class="facts">{" · ".join(facts)}{(" · " + deep) if (facts and deep) else deep}</p>' if (facts or deep) else ""
    badge = f'<span class="badge">{role} · #{int(last["rank"])}</span>'
    return f'<div class="profile" id="{sid}"><h3>{name} {badge}</h3>{strip}{img}{facts_html}{cov}</div>'


def _coverage_card_html(reg_name: str, df: pd.DataFrame) -> str:
    sub = df[df["country"] == reg_name]
    if sub.empty:
        return ""
    fw = sub["wired"].isin(["yes", "derived"]).sum()
    fu = ((sub["access"] == "free") & (~sub["wired"].isin(["yes", "derived"]))).sum()
    paid = (sub["access"] == "paid").sum()
    none = (sub["access"] == "none").sum()
    gaps = sub[sub["access"].isin(["paid", "none"])]["data_point"].head(2).tolist()
    gap_txt = (" · gap: " + "; ".join(gaps)) if gaps else ""
    return (f'<div class="cov"><span class="g">✅ {fw} wired</span>'
            f'<span class="g2">🟢 {fu} free</span>'
            f'<span class="p">💷 {paid}</span><span class="n">⛔ {none}</span>'
            f'<em>{gap_txt}</em></div>')


def _country_sections(order: list[str]) -> str:
    reg = registry.load()
    n2c = _reg_code_map()
    c2i = _code_to_iso3()
    wx = _wx_load()
    fa_iso = _faostat_iso()
    bil = cmat.load()
    reg_countries = [c for c in order if c in set(reg["country"])]
    reg_countries += [c for c in sorted(reg["country"].unique())
                      if c not in reg_countries and c != "*"]
    out = []
    for name in reg_countries:
        code = n2c.get(name)
        cname = countries.name(code) if code else name
        iso3 = c2i.get(code) if code else None
        out.append(_country_card(name, code, cname, iso3, reg, fa_iso, wx, bil))
    return "".join(out)


def _wx_load():
    try:
        from atlas import nasa_power
        return nasa_power.load()
    except Exception:
        return pd.DataFrame()


def _trade_order() -> list[str]:
    """Registry countries ordered by trade importance (max of export/import value)."""
    reg = registry.load()
    n2c = _reg_code_map()
    score = {}
    for role in ("exporter", "importer"):
        r = cs.ranking(role)
        vmap = dict(zip(r["country"], r["value_usd"]))
        for name in reg["country"].unique():
            if name == "*":
                continue
            code = n2c.get(name)
            cn = countries.name(code) if code else name
            score[name] = max(score.get(name, 0), vmap.get(cn, 0))
    return [c for c, _ in sorted(score.items(), key=lambda kv: -kv[1])]


# ----------------------------- the index (compare) -----------------------------
def _latest_season(name: str):
    """Current-season total (kt) + season label + source — the data that runs into 2026
    (committee/customs basis), where annual Comtrade stops at 2024."""
    try:
        if name == "South Africa":
            from atlas import berriesza
            t = berriesza.load()
            t = t[t["region"] == "Total"]
            if len(t):
                return float(t.iloc[0]["total_t"]) / 1000, str(t.iloc[0]["season"]), "Berries ZA"
            return None
        from atlas import campaigns
        s = campaigns.latest(name)
        if s.empty:
            return None
        for mt in ("export_total", "export_total_fresh", "export_ytd", "huelva_production", "production_total"):
            row = s[s["metric"] == mt]
            if len(row):
                return float(row.iloc[0]["value"]) / 1000, str(row.iloc[0]["season"]), str(row.iloc[0]["source"])
    except Exception:
        return None
    return None


def _index_table_html(order: list[str]) -> str:
    """One sortable row per country — the bird's-eye 'see it all (and what's missing)'.
    Empty cells are the gaps; the coverage column shows the source mix."""
    reg = registry.load()
    n2c, c2i = _reg_code_map(), _code_to_iso3()
    rank, fa_iso = cs.load(), _faostat_iso()
    try:
        from atlas import usda_gain
        fc = usda_gain.load()
    except Exception:
        fc = pd.DataFrame(columns=["country", "metric", "value_mt", "year"])
    names = [c for c in order if c != "*"] + \
            [c for c in sorted(reg["country"].unique()) if c not in order and c != "*"]
    rows = []
    for name in names:
        code = n2c.get(name)
        if not code:
            continue
        sub = rank[rank["reporter_code"] == code]
        ex = sub[sub["role"] == "exporter"].sort_values("year")
        im = sub[sub["role"] == "importer"].sort_values("year")
        lv = lambda d: float(d["value_usd"].iloc[-1]) if len(d) else 0.0
        if ex.empty and im.empty:
            continue
        prim = ex if lv(ex) >= lv(im) else im
        role = "exp+imp" if (len(ex) and len(im) and min(lv(ex), lv(im)) > 0.15 * max(lv(ex), lv(im))) \
            else ("exp" if lv(ex) >= lv(im) else "imp")
        primq = prim[prim["net_kg"] > 0]
        primq = primq if len(primq) else prim
        last = primq.iloc[-1]
        prov = cs.is_provisional(int(last["year"]))
        vol = last["net_kg"] / 1e6
        yoy = (last["net_kg"] / primq.iloc[-2]["net_kg"] - 1) * 100 if len(primq) >= 2 and primq.iloc[-2]["net_kg"] else None
        # 5-year change: latest vs 5 years prior (nearest available year with quantity)
        base_yr = int(last["year"]) - 5
        base = primq[primq["year"] == base_yr]
        if base.empty:
            base = primq[primq["year"] <= base_yr].tail(1)
        fiveyr = (last["net_kg"] / base.iloc[0]["net_kg"] - 1) * 100 if len(base) and base.iloc[0]["net_kg"] else None
        usd = last["unit_usd_kg"]; share = last["share"] * 100
        # production (FAOSTAT) + forecast (USDA) — blank = a visible gap
        iso3 = c2i.get(code)
        f = fa_iso[fa_iso["iso3"] == iso3] if iso3 else fa_iso.iloc[0:0]
        prod = f.sort_values("year")["production_t"].iloc[-1] / 1000 if len(f) else None
        fcr = fc[(fc["country"] == name) & (fc["metric"] == "production")]
        fore = fcr["value_mt"].iloc[0] / 1000 if len(fcr) else None
        # coverage mix
        rc = reg[reg["country"] == name]
        wired = int(rc["wired"].isin(["yes", "derived"]).sum())
        free = int(((rc["access"] == "free") & (~rc["wired"].isin(["yes", "derived"]))).sum())
        paid = int((rc["access"] == "paid").sum()); none = int((rc["access"] == "none").sum())

        def num(v, fmt, arrow=False):
            if v is None:
                return '<td data-v="" class="miss">—</td>'
            if arrow:
                cl = "up" if v >= 0 else "dn"
                return f'<td data-v="{v:.1f}"><i class="{cl}">{"▲" if v>=0 else "▼"}{abs(v):.0f}%</i></td>'
            return f'<td data-v="{v:.3f}">{fmt.format(v)}</td>'
        covbar = (f'<span class="mini"><i style="flex:{wired};background:#2f6f4e"></i>'
                  f'<i style="flex:{free};background:#86b08f"></i>'
                  f'<i style="flex:{paid};background:#b8860b"></i>'
                  f'<i style="flex:{none};background:#cdb4b0"></i></span>'
                  f'<small>✅{wired} 🟢{free} 💷{paid} ⛔{none}</small>')
        ls = _latest_season(name)
        ls_cell = (f'<td data-v="{ls[0]:.3f}" title="{ls[1]} · {ls[2]}"><b>{ls[0]:.0f} kt</b><br>'
                   f'<small>{ls[1]}</small></td>') if ls else '<td data-v="" class="miss">—</td>'
        rows.append((vol, f'<tr>'
            f'<td data-v="{name}"><a href="#{_slug(name)}">{name}</a></td>'
            f'<td data-v="{role}">{role}</td>'
            + f'<td data-v="{vol:.3f}">{vol:.0f} kt{"ᵖ" if prov else ""}</td>'
            + ls_cell
            + num(yoy, "", arrow=True) + num(fiveyr, "", arrow=True) + num(usd, "${:.2f}")
            + num(share, "{:.0f}%") + num(prod, "{:.0f} kt") + num(fore, "{:.0f} kt")
            + f'<td data-v="{wired}" class="covcell">{covbar}</td></tr>'))
    body = "".join(r for _, r in sorted(rows, key=lambda x: -x[0]))
    heads = ["Country", "Role", "Volume", "Latest season", "YoY", "5yr", "$/kg", "Share", "Produces", "Forecast", "Coverage"]
    numeric = [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    th = "".join(f'<th onclick="sortIdx({i},{n})">{h}</th>' for i, (h, n) in enumerate(zip(heads, numeric)))
    return (f'<table class="index" id="indexTable" data-sortcol="2" data-sortdir="desc">'
            f'<thead><tr>{th}</tr></thead><tbody>{body}</tbody></table>')


# ----------------------------- assembly -----------------------------
def _stamp(txt: str) -> str:
    return f'<p class="stamp">{txt}</p>'


def _fig_block(title: str, png: str, stamp: str, lead: str = "") -> str:
    if not png:
        return ""
    lead_html = f'<p class="lead">{lead}</p>' if lead else ""
    return (f'<div class="fig"><h3>{title}</h3>{lead_html}'
            f'<img src="{png}" alt="{title}"/>{_stamp(stamp)}</div>')


def build() -> Path:
    _style()
    today = _dt.date.today().isoformat()
    yr = _latest_final("exporter")

    kpis = "".join(f'<div class="kpi"><b>{v}</b><span>{l}</span></div>' for v, l in _kpis())
    m = cmth.load()
    # monthly rows exist past here, but are partial -- the last month whose world total is
    # within 85% of the year-ago month (i.e. the major exporters have actually reported).
    complete = "—"
    if len(m):
        g = m.groupby(m["year"] * 12 + m["month"])["net_kg"].sum()
        ok = [ym for ym in g.index if (ym - 12) in g.index and g[ym - 12] > 5e6 and g[ym] >= 0.85 * g[ym - 12]]
        if ok:
            cm_ym = max(ok); complete = f"{cm_ym // 12}-{cm_ym % 12 or 12:02d}"
    recency = (f"Annual trade complete to <b>2024</b>; <b>2025 partial</b> (Peru &amp; Chile file "
               f"their annual returns late — 2025 shows early reporters only, tagged <b>ᵖ</b>). "
               f"Monthly trade is complete only to <b>~{complete}</b> (later months are filed with a "
               f"long lag), so the relay is a multi-year average. No free trade source is current to "
               f"2026 — that needs the depth frontier (e.g. ProArándanos weekly).")

    the_year = "".join([
        _fig_block("The relay — who supplies the world each month",
                   _relay_png(),
                   "UN Comtrade monthly · supply-side export volume · free",
                   "Chile owns Jan–Feb, Spain the Northern spring, the US &amp; Canada the "
                   "summer, and Peru the great counter-season surge of Sep–Nov."),
        '<div class="row">',
        _fig_block(f"Top exporters {yr}", _ladder_png("exporter"),
                   f"UN Comtrade · {yr} (final) · free · ✓{today}"),
        _fig_block(f"Top importers {yr}", _ladder_png("importer"),
                   f"UN Comtrade · {yr} (final) · free · ✓{today}"),
        '</div>',
        '<div class="row">',
        _fig_block("Production ≠ exports", _divergence_png(),
                   "FAOSTAT × UN Comtrade · free",
                   "Who grows to eat vs. grows to ship vs. ships without growing."),
        _fig_block(f"World exporters {yr}", _choropleth_png(),
                   "UN Comtrade · export value · free"),
        '</div>',
    ])

    order = _trade_order()
    index = _index_table_html(order)
    profiles = _country_sections(order)
    matrix = _coverage_matrix_html(order)
    ceiling = _ceiling_html()

    html = _PAGE.format(today=today, year=yr, kpis=kpis, the_year=the_year, index=index,
                        profiles=profiles, matrix=matrix, ceiling=ceiling, recency=recency,
                        n_countries=profiles.count('class="profile"'))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(html, encoding="utf-8")
    return OUT


_PAGE = """<!doctype html><html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>The Global Blueberry Atlas</title>
<style>
:root{{--paper:#faf8f4;--ink:#1d1c1a;--subtle:#6c655c;--accent:#2f6f4e;--line:#e6e2db}}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--paper);color:var(--ink);
 font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;line-height:1.5}}
header{{padding:34px 22px 10px;max-width:1060px;margin:0 auto}}
h1{{font-family:Georgia,serif;font-size:2.3rem;margin:0 0 4px}}
.sub{{color:var(--subtle);font-size:1.02rem;margin:0 0 8px}}
.recency{{font-size:.84rem;color:var(--subtle);background:#fff;border:1px solid var(--line);
 border-left:3px solid var(--accent);border-radius:8px;padding:8px 12px;margin:0 0 16px}}
.kpis{{display:flex;flex-wrap:wrap;gap:10px;margin:6px 0 4px}}
.kpi{{background:#fff;border:1px solid var(--line);border-radius:10px;padding:10px 14px;min-width:120px}}
.kpi b{{display:block;font-size:1.25rem}} .kpi span{{color:var(--subtle);font-size:.82rem}}
main{{max-width:1060px;margin:0 auto;padding:8px 22px 60px}}
h2{{font-family:Georgia,serif;font-size:1.5rem;margin:34px 0 4px;border-top:2px solid var(--ink);padding-top:10px}}
.fig{{background:#fff;border:1px solid var(--line);border-radius:12px;padding:14px 16px;margin:14px 0;flex:1}}
.fig h3{{font-size:1.06rem;margin:0 0 2px}}
.fig img{{width:100%;height:auto;display:block;margin:6px 0 2px}}
.lead{{color:var(--subtle);font-size:.92rem;margin:0 0 4px}}
.row{{display:flex;gap:14px;flex-wrap:wrap}} .row .fig{{min-width:300px}}
.stamp{{color:#a59e93;font-size:.74rem;margin:4px 0 0;font-variant:small-caps;letter-spacing:.3px}}
nav{{max-width:1060px;margin:0 auto;padding:0 22px}}
nav a{{color:var(--accent);text-decoration:none;font-weight:600;margin-right:18px;font-size:.95rem}}
.profiles{{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}}
.profile{{background:#fff;border:1px solid var(--line);border-radius:12px;padding:12px 14px}}
.profile h3{{font-size:1.04rem;margin:0 0 6px;display:flex;align-items:baseline;gap:8px}}
.profile img{{width:100%;height:auto;margin:2px 0}}
.badge{{font-size:.72rem;font-weight:600;color:#fff;background:var(--accent);border-radius:20px;padding:2px 9px;text-transform:capitalize}}
.stats{{display:flex;flex-wrap:wrap;gap:14px;margin:2px 0 6px}}
.stats div{{display:flex;flex-direction:column}}
.stats b{{font-size:1.22rem;line-height:1.1}} .stats span{{font-size:.72rem;color:var(--subtle)}}
.stats i{{font-style:normal;font-size:.8rem}} .up{{color:#2f6f4e}} .dn{{color:#9c4221}}
.facts{{font-size:.82rem;color:var(--subtle);margin:4px 0 6px}} .facts b{{color:var(--ink)}}
.facts a,.cov a{{color:var(--accent);text-decoration:none}}
.cov{{font-size:.78rem;color:var(--subtle);margin:0 0 2px}}
.cov span{{margin-right:8px;font-weight:600}} .cov .g{{color:#2f6f4e}} .cov .g2{{color:#86b08f}}
.cov .p{{color:#b8860b}} .cov .n{{color:#9c4221}} .cov em{{display:block;color:#a59e93;font-style:normal;margin-top:2px}}
.matrix{{border-collapse:collapse;font-size:.92rem;width:100%}}
.matrix th{{font-weight:600;padding:5px 7px;text-align:center;color:var(--subtle);font-size:.8rem}}
.matrix th.rh{{text-align:right;white-space:nowrap;color:var(--ink);font-size:.84rem}}
.matrix td{{text-align:center;padding:5px 7px;border:1px solid #efece6;font-size:1rem}}
.index{{border-collapse:collapse;width:100%;font-size:.9rem}}
.index th{{text-align:right;padding:7px 9px;color:var(--subtle);font-size:.82rem;cursor:pointer;
 border-bottom:2px solid var(--ink);white-space:nowrap;user-select:none}}
.index th:first-child,.index td:first-child{{text-align:left}} .index th:hover{{color:var(--accent)}}
.index td{{text-align:right;padding:6px 9px;border-bottom:1px solid var(--line);white-space:nowrap}}
.index td a{{color:var(--ink);text-decoration:none;font-weight:600}} .index td a:hover{{color:var(--accent)}}
.index tr:hover td{{background:#fbfaf7}} .index .miss{{color:#cdc7bd}}
.index .covcell{{display:flex;align-items:center;gap:6px;justify-content:flex-end}}
.mini{{display:inline-flex;width:62px;height:11px;border-radius:3px;overflow:hidden}}
.mini i{{display:block}} .index small{{color:var(--subtle);font-size:.7rem}}
.ceiling{{margin:6px 0 2px}} .cbar{{display:flex;align-items:center;gap:10px;margin:5px 0;font-size:.86rem}}
.cbar span{{width:170px;color:var(--subtle)}} .cbar i{{height:14px;border-radius:3px;display:inline-block}} .cbar b{{color:var(--ink)}}
footer{{max-width:1060px;margin:0 auto;padding:20px 22px 50px;color:var(--subtle);font-size:.82rem;border-top:1px solid var(--line)}}
</style></head><body>
<header>
<h1>The Global Blueberry Atlas</h1>
<p class="sub">What the world grows, ships, and pays through the year — and exactly what
you can know about it for free. <b>Reference year {year}.</b></p>
<p class="recency">{recency}</p>
<div class="kpis">{kpis}</div>
</header>
<nav><a href="#year">The year</a><a href="#index">The index</a><a href="#countries">Countries</a><a href="#atlas">The atlas</a><a href="./index.html">Deep dive: UK ↗</a></nav>
<main>
<h2 id="year">The year</h2>
{the_year}
<h2 id="index">The index</h2>
<p class="lead">Every country on one screen — <b>click any column to sort</b>, click a name to jump to
its card. <b>Volume</b> is official Comtrade (annual, to 2024); <b>Latest season</b> is the current-season
committee/customs figure that runs into 2026 (Peru 2025/26, South Africa live, …). <b>YoY</b> and <b>5yr</b>
are volume change (1- and 5-year). Blank cells (—) are the gaps:
no FAOSTAT production, no forecast; <b>ᵖ</b> = provisional latest year (Comtrade still finalising). The coverage bar shows
each country's source mix (✅ wired · 🟢 free · 💷 paid · ⛔ none).</p>
{index}
<h2 id="countries">Countries &amp; coverage <span style="font-size:.8rem;color:#a59e93">({n_countries} profiles)</span></h2>
<p class="lead">Each country leads with the facts everyone wants — <b>volume</b> (exports &amp; imports
on one axis, the smaller flow shaded) and <b>price</b> — then partners, depth, and a coverage card.
Price is the <b>customs unit-value</b> (value ÷ net weight: FOB for exports, CIF for imports) —
an average border price, <i>not</i> retail or spot. Named exporters where the depth exists.</p>
<div class="profiles">{profiles}</div>
<h2 id="atlas">The atlas — what you can know</h2>
<p class="lead">The registry as a map: every country × data-class, flagged by access. This —
not the data — is what no one else publishes.</p>
{ceiling}
{matrix}
</main>
<footer>
Built {today} from free, public sources (UN Comtrade · FAOSTAT · USDA-FAS · NASA POWER ·
Eurostat · national NPPOs). Every figure is stamped with its source and access. Latest
~2 years of trade are provisional. · The Global Blueberry Atlas · fruit is a parameter.
</footer>
<script>
function sortIdx(n, numeric){{
  var t=document.getElementById('indexTable'), tb=t.tBodies[0], rows=Array.prototype.slice.call(tb.rows);
  var dir = (t.getAttribute('data-sortcol')==n && t.getAttribute('data-sortdir')=='asc') ? 'desc' : 'asc';
  rows.sort(function(a,b){{
    var x=a.cells[n].getAttribute('data-v'), y=b.cells[n].getAttribute('data-v');
    if(numeric){{ x=(x===''?-Infinity:parseFloat(x)); y=(y===''?-Infinity:parseFloat(y));
      return dir=='asc' ? x-y : y-x; }}
    return dir=='asc' ? (''+x).localeCompare(''+y) : (''+y).localeCompare(''+x);
  }});
  rows.forEach(function(r){{ tb.appendChild(r); }});
  t.setAttribute('data-sortcol',n); t.setAttribute('data-sortdir',dir);
}}
</script>
</body></html>"""


if __name__ == "__main__":
    p = build()
    kb = p.stat().st_size / 1024
    print(f"wrote {p}  ({kb:.0f} KB)")
